In [9]:
def binary2int(bitarray):
    '''
    Converts array of bits to integer.
    @param bitarray: Array of bits in Lower endian order.
    @returns Integer representation of the bits.
    '''
    n = len(bitarray) - 1
    numero = 0
    for bit in bitarray:
        if bit != 0:
            numero |= 1<<n
        n -= 1
    return numero

In [65]:
def binary2float(bitarray):
    '''
    Converts array of bits to 64 double floating point number. 
    Each of mantissa and exponent are expected to be in lower endian order.
    @param bitarray: Array of bits in Lower endian order.
    @returns Integer representation of the bits.
    '''
    s = bitarray[0]
    c = bitarray[1:12]
    f = bitarray[12:]
    
    xc = binary2int(c)
    xf = binary2int(f)

    #Observa que igual puedes utilizar potencias y una suma. No hay diferencia!
    return (-1)**s * 2**(xc - 1075)*((1<<52) | xf) #NOTA: 1075 = 1023 + 52

In [66]:
n  = "0100000000111011100100010000000000000000000000000000000000000000"
bits = [int(c) for c in n]
bits

[0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [67]:
binary2float(bits)

27.56640625

In [68]:
def IEEEstr(str):
    '''
    Converts a floating point number encoded in a string of '0's and '1's to its floating point value.
    '''
    bits = [int(c) for c in str]
    return binary2float(bits)

In [71]:
IEEEstr("0100000000111011100100010000000000000000000000000000000000000000")

27.56640625

In [75]:
def encodeAsInts(bitarray):
    '''
    Encodes a 64 bits double floating point number as a pair of 32 bits integers.
    '''
    n1 = bitarray[:32]
    n2 = bitarray[32:]
    return binary2int(n1), binary2int(n2)

In [76]:
encodeAsInts(bits)

(1077645568, 0)

In [81]:
binary2int(bits)

4628452471239344128

In [82]:
hex(binary2int(bits))

'0x403b910000000000'

In [83]:
hex(1077645568)

'0x403b9100'

In [85]:
hex(4628452471239344128)

'0x403b910000000000'

In [87]:
x = binary2float(bits)
np.log2(x)

4.7848392946531488

In [88]:
2**4.7848392946531488

27.566406249999993

In [89]:
x

27.56640625

In [90]:
x/2**4

1.722900390625

In [97]:
res = x/2**4

In [98]:
res

1.722900390625

In [99]:
res -= 1

In [100]:
res

0.722900390625

In [1]:
def int2bin(x, precision=64):
    '''
    @param x: Integer to represent.
    @param precision: Number of bits to extract.
    @return: the bits in a long (64 bits) integer, the result is an array in 
             Lowest endian ordering
    '''
    return [x>>i & 1 for i in range(precision - 1,-1,-1)]
        
    
def float2bin(x):
    if x == 0:
        return 64*[0]
    s = 1 - int(x/abs(x))
    x = abs(x)
    e = 0
    if x >= 2:
        while x >= 2:
            x /= 2
            e += 1
    elif x < 1:
        while x < 1:
            x *= 2
            e -= 1
    #What we are up to is to convert x to a number in the interval 1 <= x < 2
    x -= 1
    x *= 2**52
    
    return [s] + int2bin(e + 1023, precision=11) + int2bin(int(x), precision=52)
        
    

In [152]:
ans = np.array(float2bin(27.56640625))

In [153]:
''.join(map(str, ans))

'0100000000111011100100010000000000000000000000000000000000000000'

In [154]:
len(ans)

64

In [159]:
#Python manipulation of internal structure
import struct

x = 27.566406249999993
s = struct.pack('>f', x)
print(s)

b'A\xdc\x88\x00'


In [161]:
l = struct.unpack('>l', s)[0]

In [162]:
bin(l)

'0b1000001110111001000100000000000'

In [175]:
bin(ord('A')) + bin(0xdc)[2:] + bin(0x88)[2:]

'0b10000011101110010001000'

In [176]:
x = 173.3125

In [179]:
l = np.array(float2bin(x))

In [182]:
bigx = int(''.join(map(str, l)), 2)

In [183]:
bigx

4640301908051886080

In [186]:
bin(bigx)

'0b100000001100101101010100000000000000000000000000000000000000000'

In [187]:
l

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
import numpy as np
a = np.array(float2bin(3.14159))

In [6]:
a[:-52]

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
a

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0])

In [8]:
a[-52:]

array([1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0])

In [9]:
a[12:]

array([1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0])