# Eliminacion gaussiana

**Ejercicio** Implementar el algoritmo de eliminacion gaussiana siguiente

![gaussian.png](gaussian.png)

In [16]:
#First, we create a random matrix for testing purposes
import numpy as np

A = np.random.random([3,4])
n, _ = A.shape #Use _ when you want to discard some value you won't need.


T = A.copy()#T is for comparison only (T-est)

#Step 1
for i in range(n-1):
    #Step 2
    p = 0
    for p in range(i, n):
        if A[p, i] != 0:
            break
    if p == n:
        print('No unique solution exists!')
    
    #Step 3
    if p != i:
        A[[p,i],:] = A[[i,p], :]
    
    #Step 4
    for j in range(i+1, n):
        mji = A[j, i]/A[i, i] #Step 5
        A[j,:] = A[j,:] - mji*A[i,:] #Step 6
    
#Step 7
if A[n-1, n-1] == 0:
    print ('No unique solution exists!')
    
#Let's start with backward substitution
x = np.zeros([n])

x[n - 1] = A[n - 1, n]/A[n - 1, n - 1]
for i in range(n - 2, -1, -1):
    x[i] = A[i, n] - np.sum(A[i, j]*x[j] for j in range(i + 1, n))
    x[i] = x[i]/A[i, i]

Comprobamos el algoritmo, utilizando la función `solve` que viene dentro del paquete `numpy.linalg`

In [17]:
x

array([-0.5581954 , -0.92958464,  1.91668694])

In [18]:
A

array([[ 0.09706968,  0.12503283,  0.1264102 ,  0.07187634],
       [ 0.        , -0.30775564, -0.03512811,  0.21875533],
       [ 0.        ,  0.        , -0.47909351, -0.91827228]])

In [19]:
T

array([[ 0.09706968,  0.12503283,  0.1264102 ,  0.07187634],
       [ 0.60022548,  0.46537853,  0.74652298,  0.66319902],
       [ 0.96470826,  0.88757272,  0.73668432,  0.04842354]])

In [20]:
np.linalg.solve(T[:,:-1], T[:,-1])

array([-0.5581954 , -0.92958464,  1.91668694])

Ambas soluciones coinciden, asi que podemos reutilizar nuestro algoritmo definiendo una función

In [30]:
def solve(equation):
    '''
    Implements Burden's algorithm 6.1 to solve a linear system with gaussian elimination.
    @param equation: An `n x (n + 1)` numpy array representing the system of n equations.
    
    **Important:** For optimization purposes, the algorithm *will* modify the given array.
    
    @return: array of solutions of size `n`.
    
    In case the system can't be solved, it will raise a `LinearAlgebraException`.
    '''
    A = equation #Remember: python copies by reference objects.
    n, _ = A.shape #Use _ when you want to discard some value you won't need.
    
    #Step 1
    for i in range(n-1):
        #Step 2
        p = 0
        for p in range(i, n):
            if A[p, i] != 0:
                break
        if p == n:
            raise Exception('No unique solution exists!')

        #Step 3
        if p != i:
            A[[p,i],:] = A[[i,p], :]

        #Step 4
        for j in range(i+1, n):
            mji = A[j, i]/A[i, i] #Step 5
            A[j,:] = A[j,:] - mji*A[i,:] #Step 6

    #Step 7
    if A[n-1, n-1] == 0:
        raise Exception('No unique solution exists!')

    #Let's start with backward substitution
    x = np.zeros([n])

    x[n - 1] = A[n - 1, n]/A[n - 1, n - 1]
    for i in range(n - 2, -1, -1):
        x[i] = A[i, n] - np.sum(A[i, j]*x[j] for j in range(i + 1, n))
        x[i] = x[i]/A[i, i]
        
    return x




Probamos de nueva cuenta que el algoritmo funciona

In [31]:
A = np.random.random([3,4])
n, _ = A.shape #Use _ when you want to discard some value you won't need.

T = A.copy()#T is for comparison only (T-est)

x1 = solve(A)
x2 = np.linalg.solve(T[:,:-1], T[:,-1])

print(x1)
print(x2)

[-0.87247649  1.01957359  0.94056444]
[-0.87247649  1.01957359  0.94056444]


Intentemos pasar un sistema de ceros

In [32]:
A = np.zeros([3, 4])

solve(A)

/home/isra/opt/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:31: RuntimeWarning: invalid value encountered in double_scalars


array([ nan,  nan,  nan])